### ISSUE TITLE
doc: Repo desc and topics

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-exchange#112]
Desc:
- NebulaGraph Exchange is an Apache Spark application to parse data from different sources to NebulaGraph in a distributed environment. It supports both batch and streaming data in various formats and sources including other Graph Databases, RDBMS, Data warehouses, NoSQL, Message Bus, File systems, etc.

Topics:
- Graph-Database
- Spark
- NebulaGraph
- Data-Pipeline
- Data-Import
- ETL

Please @Nicole00 help review/rephrase and then let's ask @Shinji-IkariG to help edit the repo :)

**Comment by wey-gu** [comment]
@Shinji-IkariG could you please help update the repo? thanks

**Comment by Nicole00** [comment]
> Desc:
> 
> * Nebula Exchange is an Apache Spark application to parse data from different sources to NebulaGraph in a distributed environment. It supports both batch and streaming data in various formats and sources including other Graph Databases, RDBMS, Data warehouses, NoSQL, Message Bus, File systems, etc.
> 
> Topics:
> 
> * Graph-Database
> * Spark
> * NebulaGraph
> * Data-Pipeline
> * Data-Import
> 
> Please @Nicole00 help review/rephrase and then let's ask @Shinji-IkariG to help edit the repo :)

LGTM!

**Comment by Shinji-IkariG** [comment]
Desc and Topics have been modified, thanks to Wey for the suggestion～

**Comment by wey-gu** [comment]
> Desc and Topics have been modified, thanks to Wey for the suggestion～

Thanks a lot @Shinji-IkariG !
