### ISSUE TITLE
Not enough space to cache rdd in memory warning

### ISSUE THREAD

**Issue by porscheme** [vesoft-inc/nebula-exchange#135]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**
I am running a nebula-exchange with spark-operator, and I got Not enough space to cache '' in memory warning.

**Your Environments (__required__)**
- nebula cluster info
v3.4.0
graphd: 3 (128 Gb, 2 TB SSD Drive)
metad: 3 (128 Gb, 2 TB SSD Drive)
storaged: 5 (128 Gb, 2 TB SSD Drive)

- spark-operator
driver: 1 (16 GB)
Executor: 20 (140 GB)

* OS: `uname -a`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

```
{"level":"WARN","timestamp":"2023-03-30 23:38:41,633","thread":"Executor task launch worker for task 5592.0 in stage 1.0 (TID 5593)","message":"Not enough space to cache rdd_6_5592 in memory! (computed 24.6 MiB so far)"}
{"level":"WARN","timestamp":"2023-03-30 23:38:41,633","thread":"Executor task launch worker for task 5592.0 in stage 1.0 (TID 5593)","message":"Persisting block rdd_6_5592 to disk instead."}
{"level":"WARN","timestamp":"2023-03-30 23:38:42,289","thread":"Executor task launch worker for task 5580.0 in stage 1.0 (TID 5581)","message":"Not enough space to cache rdd_6_5580 in memory! (computed 94.3 MiB so far)"}
{"level":"WARN","timestamp":"2023-03-30 23:38:42,289","thread":"Executor task launch worker for task 5580.0 in stage 1.0 (TID 5581)","message":"Persisting block rdd_6_5580 to disk instead."}
{"level":"WARN","timestamp":"2023-03-30 23:38:43,286","thread":"Executor task launch worker for task 5580.0 in stage 1.0 (TID 5581)","message":"Not enough space to cache rdd_6_5580 in memory! (computed 94.3 MiB so far)"}
{"level":"WARN","timestamp":"2023-03-30 23:38:44,604","thread":"Executor task launch worker for task 5592.0 in stage 1.0 (TID 5593)","message":"Not enough space to cache rdd_6_5592 in memory! (computed 94.2 MiB so far)"}
```

**Comment by Nicole00** [comment]
you can set less executor-cores for each executor and less executor number， set more executor-memory for each executor

**Comment by QingZ11** [comment]
I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
