### ISSUE TITLE
studio v3.7.0 查看schema ddl 显示存在问题

### ISSUE THREAD

**Issue by HarLin97** [vesoft-inc/nebula-exchange#141]
问题截图：
![image](https://github.com/vesoft-inc/nebula-exchange/assets/29650805/aa83f257-6de0-40f5-8648-9836d2f59153)
环境：
windows 11
docker-compose
版本:
nebula v3.5.0
studio v.3.7.0

**Comment by wey-gu** [comment]
Hi @HarLin97 do you mean the ddl field was covered/not shown from the beginning?

I'll move this issue to studio repo
