### ISSUE TITLE
Get error with the fix from https://github.com/vesoft-inc/nebula-exchange/pull/145 

### ISSUE THREAD

**Issue by chenweisomebody126** [vesoft-inc/nebula-exchange#146]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

Once I merged the https://github.com/vesoft-inc/nebula-exchange/pull/145 PR into my branch, I still got the error 
```
│ Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.String com.google.common.net.HostAndPort.getHost()'                                                                             │
│     at com.vesoft.exchange.common.GraphProvider.$anonfun$new$1(GraphProvider.scala:36)    ```

**Your Environments (__required__)**

version Nebula Exchange 3.0

**Comment by wey-gu** [comment]
Would you mind fixing this :-D, Wei?

cc @Nicole00

**Comment by Nicole00** [comment]
> **Please check the FAQ documentation before raising an issue**
> 
> **Describe the bug (required)**
> 
> Once I merged the #145 PR into my branch, I still got the error
> 
> ```
> │ Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.String com.google.common.net.HostAndPort.getHost()'                                                                             │
> │     at com.vesoft.exchange.common.GraphProvider.$anonfun$new$1(GraphProvider.scala:36)    ```
> 
> **Your Environments (__required__)**
> 
> version Nebula Exchange 3.0
> ```

Maybe the java client with snapshot version in your local repository is not the latest， please use `-U` in your mvn command to force get the latest dependency from remote repository.

**Comment by Nicole00** [comment]
Hi @chenweisomebody126 how's it going? using the latest java client dependency can resolve your problem?

**Comment by QingZ11** [comment]
@chenweisomebody126 hi, I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
