### ISSUE TITLE
MySQLReader url is fixed

### ISSUE THREAD

**Issue by BleakStone** [vesoft-inc/nebula-exchange#180]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**
When I use MySQLReader, the url is fixed, for example
val url =
s"jdbc:mysql://${mysqlConfig.host}:${mysqlConfig.port}/${mysqlConfig.database}? useUnicode=true&characterEncoding=utf-8",
But do I want to add more mysql parameters, such as
“useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai” and so on, it should change the url parameter to a custom configurable parameter

**Your Environments (__required__)**

* OS: `uname -a`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by BleakStone** [comment]
Similarly, change the driver argument to custom

**Comment by Nicole00** [comment]
Thank you for your question. 
The mysql data source encapsulates the URL internally based on open parameters.  If you want a more flexible use, maybe you could use the `jdbc` to import data and it has  more complete configurations.
