### ISSUE TITLE
Support reading from phoenix in nebula exchange

### ISSUE THREAD

**Issue by byf-code** [vesoft-inc/nebula-exchange#4]
The nebula exchange can import data from hive or others, but no phoenix. So is there a plan to  carry this out?

**Comment by Nicole00** [comment]
> The nebula exchange can import data from hive or others, but no phoenix. So is there a plan to carry this out?

please use spark connector to read from phoenix and write to nebula. Refer https://github.com/vesoft-inc/nebula-spark-connector/blob/master/example/src/main/scala/com/vesoft/nebula/examples/connector/NebulaSparkWriterExample.scala
