### ISSUE TITLE
2.5.0版本中，下载pulsar-spark-connector_2.11，解压到本地Maven库的目录io/streamnative/connectors中

### ISSUE THREAD

**Issue by chensongcan** [vesoft-inc/nebula-exchange#89]
2.5.0版本中，”下载pulsar-spark-connector_2.11，解压到本地Maven库的目录io/streamnative/connectors中“是什么意思？我的maven目录下并没有io这个目录，请问是解压到哪里呢

**Comment by Nicole00** [comment]
> 2.5.0版本中，”下载pulsar-spark-connector_2.11，解压到本地Maven库的目录io/streamnative/connectors中“是什么意思？我的maven目录下并没有io这个目录，请问是解压到哪里呢

没有io/streamnative目录 就自己建一个
